app/controllers/admin/attendances_controller.rb, app/models/attendance.rb, app/models/klass.rb, app/models/student.rb, app/views/admin/attendances/_form.html.erb, app/views/admin/attendances/edit.html.erb, app/views/admin/attendances/index.html.erb, app/views/admin/attendances/new.html.erb, app/views/admin/attendances/show.html.erb, config/routes.rb, db/migrate/20181216225409_create_attendances.rb, db/migrate/20181216230432_create_join_table_attendances_students.rb, db/migrate/20181216235019_create_join_table_attendances_klasses.rb, db/migrate/20181216235841_add_new_column_to_students.rb, db/schema.rb
First, we must have a Klass with students, after that we gonna have a link `klass/:id/attendances`and inside that we can create the subject/attendances, then for each attendance/subject we must check the student that was attending that subject.
=> Created students attendances

app/views/admin/attendances/index.html.erb, app/views/admin/klasses/index.html.erb, app/views/admin/students/index.html.erb, app/views/admin/teachers/index.html.erb
=> add custom buttons to the index pages

app/controllers/admin/dashboard_controller.rb, app/controllers/admin/justifications_controller.rb, app/controllers/justifications_controller.rb, app/helpers/justification_helper.rb, app/models/justification.rb, app/views/admin/dashboard/index.html.erb, app/views/admin/justifications/_form.html.erb, app/views/admin/justifications/edit.html.erb, app/views/admin/justifications/show.html.erb, app/views/common/_admin_left_side_nav.html.erb, app/views/justifications/_form.html.erb, app/views/justifications/new.html.erb, config/initializers/simple_form.rb, config/locales/simple_form.pt-BR.yml, config/routes.rb, db/migrate/20181217232331_create_justifications.rb, db/migrate/20181218000600_create_active_storage_tables.active_storage.rb, db/migrate/20181218023255_add_column_to_justifications.rb, db/schema.rb
Added a public form which is allowed to attach an image file, also in the admin section we can see the justifications and accept or not.
FORM
DASHBOARD
DETAILS
=> Created a justification way for the students

app/controllers/admin/attendances_controller.rb, app/controllers/admin/klasses_controller.rb, app/models/student.rb, app/views/admin/attendances/index.html.erb, app/views/admin/klasses/index.html.erb, app/views/admin/klasses/show.html.erb
=> Added counter to check the student attendance

app/controllers/admin/attendances_controller.rb, app/controllers/admin/klasses_controller.rb, app/controllers/admin/students_controller.rb, app/helpers/application_helper.rb, app/helpers/student_helper.rb, app/models/klass.rb, app/models/situation.rb, app/models/student.rb, app/views/admin/attendances/_form.html.erb, app/views/admin/attendances/index.html.erb, app/views/admin/klasses/_form.html.erb, app/views/admin/klasses/show.html.erb, app/views/admin/students/_form.html.erb, app/views/admin/students/index.html.erb, config/routes.rb, db/migrate/20190113220715_add_column_to_students.rb, db/migrate/20190114124550_add_column_to_attendances.rb, db/migrate/20190123171129_create_situations.rb, db/migrate/20190218183539_remove_column_from_students.rb, db/schema.rb, spec/factories/situations.rb, spec/models/situation_spec.rb
This PR will do: 
1- Disable student and keep the history
2- Fix students attendance counter
3- Added a new field for attendances - > realized_at
4- Removed unnecessary columns
=> Added action to disable students keeping the history

app/controllers/admin/dashboard_controller.rb, app/views/admin/dashboard/index.html.erb
=> Add a birthday list on Dashboard

app/models/student.rb, app/views/admin/klasses/show.html.erb
=> Showing which classes the student lost

app/controllers/admin/dashboard_controller.rb, app/views/admin/dashboard/index.html.erb
=> fix students counter to dashboard

app/controllers/justifications_controller.rb, app/models/student.rb, app/views/admin/klasses/show.html.erb, app/views/justifications/_form.html.erb, db/migrate/20190822215037_add_klasses_column_to_justifications.rb, db/schema.rb, spec/factories/attendances.rb, spec/factories/justifications.rb, spec/models/student_spec.rb
**Issue #27** 
Actually we have this scenario:
If the student who not attendance the class but sent us a justification that was accepted by our stuff, the system should not calculate on the no attendance.
Just the student with no attendance on that class who had your justification denied should be add on the total number of your no attendance history.
=> Change no attendance counter to work with accepted justifications

app/views/admin/attendances/_form.html.erb
Issue #47
The list of students inside the attendance class must be ordered alphabetically.
=> Students list ordered by ASC

app/views/student/dashboard/index.html.erb
=> remove from student dashboard a box with counts

app/views/common/_top_bar_nav.html.erb, app/views/student/dashboard/index.html.erb
=> change top menu and button size on student dashboard

.travis.yml
Sending notifications to slack when build passed or when to get failure.
=> New options to Travis CI

Gemfile, Gemfile.lock
More information: https://devcenter.heroku.com/articles/language-runtime-metrics-ruby#getting-started
=> Enable Heroku Ruby Metrics

.rubocop.yml, app/models/student.rb, spec/helpers/application_helper_spec.rb, spec/models/admin_spec.rb, spec/models/klass_spec.rb, spec/models/student_spec.rb, spec/requests/admin/attendances_spec.rb, spec/requests/admin/justifications_spec.rb, spec/requests/admin/klasses_spec.rb, spec/requests/admin/students_spec.rb, spec/requests/admin/teachers_spec.rb, spec/requests/sessions_spec.rb
This PR adds RuboCop suggestions into the code following the Ruby Style Guide.
* Changed Specs files;
* Changed RuboCop settings;
* Changed Student's model;
* Run `rubocop` on your console;
* Run `rspec` on your console.
=> RuboCop suggestions accepted

app/controllers/admin/klasses_controller.rb, app/views/admin/klasses/_absences.html.erb, app/views/admin/klasses/show.html.erb, spec/requests/admin/klasses_spec.rb
This PR adds a modal on Classes Details to visualize the student's absences.
- Removed student's absences content from the show view;
- Create a partial with modal structure and add it student's absence content inside;
You should go to Classes(Turmas) >> List All(Listar Todas) >> Click it on a Class Details (Detalhes) >> View (Visualizar).
=> Add a modal on Student's absences

app/views/admin/klasses/_absences.html.erb, app/views/admin/klasses/show.html.erb
This PR will fix a modal problem that's not rendering correct student information.
You must go to Classes >> List All Classes >> Details >> Student/View
=> [FIX] Modal is not getting the student id

app/models/student.rb
This PR is doing a small refactoring on Student's model.
DRY the student's model!
=> Small refactoring on Student model

app/views/student/dashboard/index.html.erb, app/views/student/justifications/index.html.erb
Quick fix on student dashboard to show empty messages on absences box
- change student dashboard index
- change the title on student justification index
After login as a student, you will see a message on absences box saying: "you don't have any absence"
=> Quick fix on student dashboard to show empty message

app/controllers/student/justifications_controller.rb
This PR is changing the student class drop-down menu to show only the classes who the student is subscribed.
- change student justification controller
You must log in as a Student then go to new justification and click it on the classes drop-down menu.
=> Change Student justification form

app/controllers/admin/attendances_controller.rb, app/models/student.rb, app/views/admin/attendances/index.html.erb, app/views/admin/klasses/_absences.html.erb, app/views/admin/klasses/show.html.erb, app/views/student/dashboard/index.html.erb, db/migrate/20191031174013_remove_reliazed_at_date_from_absences_name.rb, db/schema.rb, spec/models/student_spec.rb
This PR the absence data on a modal to a table
* Refactoring the `show_attendances` method to return a hash with name and date when the class was realized
* Change the view to display a responsive data
* Change the student Dashboard
* When open the Absence modal, the classes should be displayed on a table
* When open the Student dashboard, the classes should be displayed on a table
=> Move klasses to table on Absence modal

app/views/student/dashboard/index.html.erb
*improve student dashboard to see which class was the absence*
*student dashboard view*
*sign in as a student and check it out the absences list on the dashboard*
=> small adjust on absences on the student dashboard

app/models/klass.rb, app/views/admin/attendances/_form.html.erb, spec/models/klass_spec.rb
*Show only active student on the Absence list*
*As Admin, firstly you must disable the student, to do that follow the steps below:*
1. Go to Classes List, then click it on the Edit button, grab a student and click it on the disable button.
2. Go back to the Class list, then click it on Attendances after that goes to Edit to see the students list.
=> Show only active student on the absence list

app/controllers/admin/dashboard_controller.rb, app/models/klass.rb, app/views/admin/dashboard/index.html.erb, spec/models/klass_spec.rb
*Admin will see the birthday list split by Active Class and Students.*
*Sign in as Admin and check it out on the dashboard the Birthday List by Month.*
=> Change on Admin dashboard the birthday list

app/models/klass.rb, app/views/admin/dashboard/index.html.erb
*fix birthday list to show only active class*
*describe what you've changed*
=> [FIX] birthday list was showing disabled class

app/models/klass.rb, app/views/admin/klasses/_form.html.erb, app/views/admin/klasses/show.html.erb
*It was found the following case: If the student was disabled on an old Class, the student was not appearing on the presence list of the new Class*
*Changed the method on Klass Model to check the student's situation correctly.*
=> [FIX] Presence list

Gemfile, Gemfile.lock
*Upgrading Ruby version from 2.6 to 2.7*
*Changed Ruby version and updated some gems such as: mime magic and boot snap*
=> Upgrade Ruby 2.6 to 2.7

Dockerfile, config/database.yml.sample, docker-compose.yml
*Using docker to make things easiest*
*Created Dockerfile and docker-composer file*
*Install docker on your machine, I suggest using the docker plugin on the VSCode as well than run it.*
=> Using Docker
